CTCP-3713: wip implement P5 to P4 conversion
hmrc/transit-movements-trader-manage-documents pull request #84
Opened 2023-08-16 11:01 UTC by MatthewAlexanderBeck

2023-09-24 19:11 UTC, BledarFeratiEY commented
<img width="543" alt="image" src="https://github.com/hmrc/transit-movements-trader-manage-documents/assets/104501743/65177877-e2ed-4a7d-a148-3dce103473bc">
<img width="543" alt="image" src="https://github.com/hmrc/transit-movements-trader-manage-documents/assets/104501743/e8067780-a785-4858-bf40-d80fd8b4d609">

2023-09-24 20:44 UTC, joecefnhedog requested changes

2023-09-24 20:44 UTC, joecefnhedog commented on app/controllers/testOnly/TransitAccompanyingDocumentP5Controller.scala
> +          } yield genPdf match {
I think it may also be good to keep the logic out of the yield {}, maybe pull that out into a separate function as well:

2023-09-24 20:44 UTC, joecefnhedog commented on app/models/P5/departure/ConsignmentItem.scala
> +      .get
are we sure the get will not fail? Should we provide a default? Or maybe ConsignmentItem.Packaging should be a NonEmptyList too.

2023-09-24 20:44 UTC, joecefnhedog commented on app/models/P5/departure/Item.scala
> +//  implicit val formats: OFormat[Item] = Json.format[Item]
can this go

2023-09-24 20:44 UTC, joecefnhedog commented on app/models/P5/departure/MessageData.scala
> +        case 0 => ""
could this have been done for `departureTransportMeansIdentity` too? The one in app/models/P5/departure/Consignment.scala

2023-09-24 20:44 UTC, joecefnhedog commented on app/services/conversion/TransitAccompanyingDocumentConversionService.scala
> +    } yield (
Just a similar comment on the yield, can we move the logic up into the for comp and maybe split into a separate function if it looks to big

2023-09-24 20:44 UTC, joecefnhedog commented on app/models/P5/departure/Consignment.scala
> +          case 1 => s"${departureTransportMeansList.head.toString}"
you could also do:
 ```
departureTransportMeansList match {
          case head::Nil => s"${head.toString}"
          case ::(head, tail) => s"${head.toString}..."
          case Nil => ""
        }
```
just so we are not calling `.head`, but I'm happy with either if we can handle the empty list case

2023-09-24 20:44 UTC, joecefnhedog commented on app/services/conversion/TransitAccompanyingDocumentConverter.scala
> +            viewmodels.TransitAccompanyingDocumentP5TransitionPDF(
This is starting to look big, can we try and split it up a bit. Maybe for each parameter in the case class `TransitAccompanyingDocumentP5TransitionPDF` we have single line or else defer to a function which handles the logic

2023-09-25 08:58 UTC, joecefnhedog approved these changes
Happy for the comments to be addressed separatly

2023-09-25 08:58 UTC, merged